version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    environment:
      WOW_SERVER_HOST: "server"
      WOW_SERVER_PORT: "8080"
      TIME_FOR_RETRY: 5s
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    environment:
      WOW_HOST: "server"
      WOW_PORT: "8080"
    expose:
      - 8080
